{{- if not .Values.messagingSystem.external.enabled }}
{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameNats" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1 #TODO: https://github.com/opencloud/opencloud-charts/issues/12
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- if and $.Values.services.nats.persistence.enabled $.Values.services.nats.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          {{- include "oc.initContainerImage" $ | nindent 10 }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          {{- include "oc.initChownDataCommand" $ | nindent 10 }}
          volumeMounts:
          - name: {{ include "oc.persistence.dataVolumeName" . }}
            mountPath: /var/lib/opencloud
      {{ end }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            - name: OC_RUN_SERVICES
              value: nats

            - name: NATS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: NATS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: NATS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            # Tracing not yet implemented: https://github.com/opencloud/opencloud/issues/6174
            # - name: NATS_TRACING_ENABLED
            #   value: "{{ .Values.tracing.enabled }}"
            # - name: NATS_TRACING_TYPE
            #   value: {{ .Values.tracing.type | quote }}
            # - name: NATS_TRACING_ENDPOINT
            #   value: {{ .Values.tracing.endpoint | quote }}
            # - name: NATS_TRACING_COLLECTOR
            #   value: {{ .Values.tracing.collector | quote }}

            - name: NATS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: NATS_NATS_HOST
              value: "0.0.0.0"
            - name: NATS_NATS_PORT
              value: "9233"

            - name: NATS_DEBUG_ADDR
              value: 0.0.0.0:9234

            - name: OC_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.transferSecret" . }}
                  key: transfer-secret

            - name: OC_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: OC_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.machineAuthAPIKeySecret" . }}
                  key: machine-auth-api-key

            - name: OC_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: nats
              containerPort: 9233
            - name: metrics-debug
              containerPort: 9234

          volumeMounts:
            - name: {{ include "oc.persistence.dataVolumeName" . }}
              mountPath: /var/lib/opencloud
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        {{- include "oc.caVolume" $ | nindent 8}}
        {{- include "oc.persistence.dataVolume" . | nindent 8 }}
{{- end }}
