{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameUserlog" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.cors" . |nindent 12 }}
            {{- include "oc.events" . | nindent 12 }}
            {{- include "oc.persistentStore" . | nindent 12 }}

            - name: OC_RUN_SERVICES
              value: userlog

            - name: OC_DEFAULT_LANGUAGE
              value: {{ default "en" .Values.features.language.default | quote }}

            - name: USERLOG_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: USERLOG_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: USERLOG_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            # Tracing not yet implemented: https://github.com/opencloud/opencloud/issues/6177
            # - name: USERLOG_TRACING_ENABLED
            #   value: "{{ .Values.tracing.enabled }}"
            # - name: USERLOG_TRACING_TYPE
            #   value: {{ .Values.tracing.type | quote }}
            # - name: USERLOG_TRACING_ENDPOINT
            #   value: {{ .Values.tracing.endpoint | quote }}
            # - name: USERLOG_TRACING_COLLECTOR
            #   value: {{ .Values.tracing.collector | quote }}

            - name: USERLOG_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: USERLOG_HTTP_ADDR
              value: 0.0.0.0:8080

            - name: USERLOG_DEBUG_ADDR
              value: 0.0.0.0:9210

            - name: OC_SERVICE_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "config.authService" . }}
                  key: service-account-id

            - name: OC_SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.serviceAccountSecret" . }}
                  key: service-account-secret

            {{- if .Values.secretRefs.globalNotificationsSecretRef }}
            - name: USERLOG_GLOBAL_NOTIFICATIONS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.globalNotificationsSecret" . }}
                  key: notifications-secret
            {{- end }}

            - name: OC_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: USERLOG_MAX_CONCURRENCY
              value: {{ .Values.services.userlog.maxConcurrency | quote }}

            - name: OC_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.transferSecret" . }}
                  key: transfer-secret

            - name: OC_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: OC_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.machineAuthAPIKeySecret" . }}
                  key: machine-auth-api-key

            - name: OC_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 8080
            - name: metrics-debug
              containerPort: 9210

          volumeMounts:
            {{- include "oc.caPath" $ | nindent 12}}

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:

        {{- include "oc.caVolume" $ | nindent 8}}
