{{- include "oc.basicServiceTemplates" (dict "scope" . "appName" "appNameAppRegistry" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "oc.metadata" . }}
spec:
  {{- include "oc.selector" . | nindent 2 }}
  replicas: 1 #TODO: https://github.com/opencloud/opencloud-charts/issues/48
  {{- include "oc.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "oc.templateMetadata" (dict "scope" $ "configCheck" true) | nindent 4 }}
    spec:
      {{- include "oc.affinity" $ | nindent 6 }}
      {{- include "oc.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "oc.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "oc.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "oc.image" $ | nindent 10 }}
          command: ["opencloud"]
          args: ["server"]
          {{- include "oc.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "oc.serviceRegistry" . | nindent 12 }}
            {{- include "oc.events" . | nindent 12 }}

            - name: OC_RUN_SERVICES
              value: appregistry

            - name: APP_REGISTRY_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: APP_REGISTRY_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: APP_REGISTRY_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: APP_REGISTRY_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: APP_REGISTRY_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: APP_REGISTRY_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: APP_REGISTRY_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: APP_REGISTRY_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: APP_REGISTRY_GRPC_ADDR
              value: 0.0.0.0:9242
            - name: APP_REGISTRY_DEBUG_ADDR
              value: 0.0.0.0:9243

            - name: OC_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.transferSecret" . }}
                  key: transfer-secret

            - name: OC_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: OC_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.machineAuthAPIKeySecret" . }}
                  key: machine-auth-api-key

            - name: OC_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

            {{- include "oc.caEnv" $ | nindent 12}}

          {{- include "oc.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9242
            - name: metrics-debug
              containerPort: 9243

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: configs
              mountPath: /etc/opencloud
            {{- include "oc.caPath" $ | nindent 12}}
            - name: messaging-system-ca
              mountPath: /etc/opencloud/messaging-system-ca
              readOnly: true

      {{- include "oc.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: configs
          configMap:
            name: {{ .appName }}-config
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{- include "oc.caVolume" $ | nindent 8}}