{{- if not .Values.secretRefs.urlSigningSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "url-signing-secret" (randAlphaNum 30) }}
{{- include "oc.secret" (dict "scope" . "name" "url-signing-secret" "params" $params)}}
{{- end }}